on:
  push:
    branches:    
      - master
name: lighthouse-score docker build
jobs:
  lighthouse-scoreIsMaster:
    name: lighthouse-score is master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lighthouse-score docker registry
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: lighthouse-score action
      uses: docker://cdssnc/touched-github-action:latest
      with:
        args: lighthouse-score/**
    - name: build lighthouse-score
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: build -t cdssnc/lighthouse-score-github-action ./lighthouse-score
    - name: push lighthouse-score
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: push cdssnc/lighthouse-score-github-action
