on:
  push:
    branches:    
      - master
name: Backup to S3
jobs:
  branchIsMaster:
    name: Branch is master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Uploads your workspace to S3
      uses: ./diefenbunker
      env:
        AWS_KEY: ${{ secrets.AWS_KEY }}
        AWS_SECRET: ${{ secrets.AWS_SECRET }}
        S3_DESTINATION: s3://cds-github/diefenbunker/
