on:
  push:
    branches:    
      - master
name: tf-lint docker build
jobs:
  tf-lintIsMaster:
    name: tf-lint is master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: tf-lint docker registry
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: tf-lint action
      uses: docker://cdssnc/touched-github-action:latest
      with:
        args: tf-lint/**
    - name: build tf-lint
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: build -t cdssnc/tf-lint-github-action ./tf-lint
    - name: push tf-lint
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: push cdssnc/tf-lint-github-action
